version: '3.7'
services:
  mysql:
    container_name: e_commerce_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: e_commerce
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql:rw

# docker exec -it e_commerce_mysql mysql -uroot -p